# Generated by Django 3.0.5 on 2020-08-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemmodel',
            name='item_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
