# Generated by Django 3.0.5 on 2020-08-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20200805_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemmodel',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
