# Generated by Django 3.0.5 on 2020-08-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20200810_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemmodel',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
