# Generated by Django 3.0.5 on 2020-08-14 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0008_collectionitemmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitemmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
